### ISSUE TITLE
Announcement Setting 'Event Only'

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#101]
**Is your improvement request related to a problem? Please describe.**
There is no way to get event details to display automatically.

**Describe the solution you'd like**
A setting to have an announcement display the full event info instead of the announcement info.

**Describe alternatives you've considered**
A fully separate command to cause events to display at start time.

**Additional context**
![image](https://user-images.githubusercontent.com/19196582/115310003-0f7e2600-a13b-11eb-815f-6d0b328f0613.png)

**Comment by NovaFox161** [comment]
I genuinely don't know what I was thinking when I made announcements and didn't think people would want this functionality.

Gonna add it into this release for sure since it shouldn't be too hard. Probably going to be one of the last changes in the current milestone as its already way too big and needs to get released, but I feel like this would be a huge quality of life enhancement and shouldn't be delayed to the next milestone release.

**Comment by NovaFox161** [comment]
Moving this to 4.1.1 milestone. Same reasoning as the previous 2 issues (#80 and #85) due to feature creep

**Comment by NovaFox161** [comment]
This has been added in code as a form of "announcement style" (similar in concept to how we handled "simple" announcements).

While the code is not currently used, it is implemented in code and will be getting used soon once I clean up and convert the announcement code to kotlin and using some of our new internal entities so that the announcement system won't need another rewrite to support multiple calendars/other calendar hosts.

**Comment by NovaFox161** [comment]
Fully implemented now with the rewrite of the announcement system
