### ISSUE TITLE
Enable Slash Commands

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#102]
**Is your feature request related to a problem? Please describe.**
Inputting multiple commands to create events and announcements is arduous.

**Describe the solution you'd like**
Discord introduced Slash Commands for bots this year which make for a much better UI/UX, and doesn't have to be built from scratch.

**Describe alternatives you've considered**
Rebuild our Discord UI  ourselves.

**Additional context**
https://discord.com/developers/docs/interactions/slash-commands

**Comment by NovaFox161** [comment]
Unfortunately not as simple as I would love, but it actually does require fully rewriting the command handling inside of DisCal.

What I plan on doing eventually is just slowly adding existing commands as slash commands since it requires a rebuild from the ground up and would allow me to actually follow good design practices and conventions since the current command system is built on a really old design that just isn't maintainable.

**Comment by smnc** [comment]
Guess I better learn Java so I can help 😅

**Comment by NovaFox161** [comment]
Dannie is working on another bot right now that has a really great system for handling slash commands. 

Implementing slash commands in DisCal will likely be deferred until she finishes up that system so we can use that code for this (since that project is open source and will be owned and maintained by DreamExposure).

**Comment by NovaFox161** [comment]
Refer to #111
