### ISSUE TITLE
Support past event creation

### ISSUE THREAD

**Issue by notsag** [DreamExposure/DisCal-Discord-Bot#103]
**Is your feature request related to a problem? Please describe.**
I'm currently using discal as a planning and shared calendar. Sometimes, the event creation step is missed and we cannot add it afterwards.

**Describe the solution you'd like**
I'd like to be able to create an event in the past.

**Describe alternatives you've considered**
None except don't forget to create the event on time.

**Additional context**
None.

**Comment by NovaFox161** [comment]
The reason we disallowed past event creation was because we assumed making an event in the past was likely a mistake rather than intentional. 

Is this a requested enough feature to remove that limit? Should there be some sort of warning that its in the past? or just accept it as "assume the user is correct"?

**Comment by smnc** [comment]
I'd definitely think adding a warning would be a good design choice, if for no other reason than to head off a pile of "my event didn't go off" support requests.

**Comment by NovaFox161** [comment]
Now supported in the slash command version of the command. When setting an event's start or end time that happens to be in the past, a warning is shown, but the past time is accepted as being valid.
