### ISSUE TITLE
Premium Discord Status Reverting

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#66]
## *Who* is the bug affecting?
Admin in specific server 455516225288536064

## *What* is affected by this bug?
The Bot

## *When* does this occur?
Appears to be random

## *Where* on the platform does it happen?
Database (presumably)

## *How* do we replicate the issue?
Not sure yet

## Expected behavior (i.e. solution)
When bot is unlocked in a specific server, unlocked status should stick

## Other Comments
Not a high priority, bot can still access linked calendar, although Server branding is gone.

**Comment by NovaFox161** [comment]
Cannot replicate in my own environments. I thought it may have been due to the local cache being up-to-date, but never being written to database, but if that were the case it wouldn't persist across shard reboots which it has been. 

Could be some database issue and not code. Unsure and cannot consistently replicate. Possibly related to #65

**Comment by NovaFox161** [comment]
This should be fixed in commit dbd6771d557def6ef9e8cb4d51871ffd2b42fe5c and has been deployed as a snapshot/hot-fix version as this was too urgent to wait for the 4.1.0 milestone.

Issue was related to not saving new guild settings due to empty Mono flow making the null/present check redundant.
