### ISSUE TITLE
!events <# of days>

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#80]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A system to limit the number of events by date range or display the events for th next _x_ # of days

**Describe alternatives you've considered**
Using the calendar display

**Additional context**

**Comment by NovaFox161** [comment]
What would be the appropriate range to limit this too? a week? 2 weeks? A month?
While this won't have any real effect on the bot itself, because the query to get the events will be a limited range pull, and the requests to create the messages will be automatically rate limited. A user requesting all events in a month in a server with a very active calendar could be waiting for awhile for all the messages to post. 

And how would the command look. Perhaps `!events days 7` and for a date range `!events 2020/12/01-2020/12/31`?? 

Once those questions are answered, I can work on building it into the bot

**Comment by NovaFox161** [comment]
@smnc Any suggestions here. I'd love to get it added >.<

**Comment by smnc** [comment]
I think for the rate-limit issue, maybe we cap the number of total events the bot will display based on the rate-limits instead of hard-coding in a date range limit? When the bot hits the limit we have the bot display the calendar link with a message saying something like 
> DisCal has reached the limit of messages Discord will allow it to display right now, please adjust your date range or use the calendar link below to see more events."

It'd be cleaner and probably head-off a bunch of support tickets, lol.

And for the syntax, both? I think `!event days 7` to see the next week will be the main use, but the ability to specify a date range would be invaluable for some guilds.

**Comment by NovaFox161** [comment]
Oh shit, didn't think about that possibility at all. That should be a pretty solid solution honestly.

**Comment by smnc** [comment]
This is my sweet spot - just enough programming knowledge to know _how_ stuff works, without knowing how to actually _do_ it, lol.

**Comment by NovaFox161** [comment]
So, think its gonna be:

- `!events days 7` to show up to 10 of the upcoming events in the next 7 days
- `!events date 2021/04/01-2021/05/01` to show up to 10 of the events in that time period.
- There will be a message if more than 10 events have been found, indicating to see the rest to click the link to view the calendar on the website

Think that works? If so I should be able to add it within this milestone.

**Comment by smnc** [comment]
Sounds great!

**Comment by NovaFox161** [comment]
Moving this to the 4.1.1 milestone. Same reasoning as #85 due to feature creep.

**Comment by NovaFox161** [comment]
Added in commit ece73a8dd0c90bc465d487b4dea68643147def32. will be deployed as per milestone
