### ISSUE TITLE
Bugged Event Editor

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#91]
## *Who* is the bug affecting?
Users trying to edit exitisting events

## *What* is affected by this bug?
The bot

## *When* does this occur?
Ehen editing an existing event

## *Where* on the platform does it happen?
Event editor/creator

## *How* do we replicate the issue?
Need to to do more investigation to nail down circumstances

## Expected behavior (i.e. solution)
Should be able to event existing events.

**Comment by AtomicSpuds** [comment]
Just in case it helps, if I create an event, and then attempt to change the start date. There is part of the event that is saved with the eventid_startdate somewhere and thus it doesn't actually change the start date. other bits of the event (summary, description, frequency) seem to update fine.

**Comment by NovaFox161** [comment]
Issue #44 is a case of this, but there are definitely several more that I have not been able to replicate.


> 
> 
> Just in case it helps, if I create an event, and then attempt to change the start date. There is part of the event that is saved with the eventid_startdate somewhere and thus it doesn't actually change the start date. other bits of the event (summary, description, frequency) seem to update fine.
If its a recurring event, event ID's of the child events do have the date/time appended onto the end of the event ID as you mentioned (`eventid_startdate`) but that is a google thing and not something we control.
I don't think that is at all related to event editing failing, just an oddity of google's system that we can't change. So while the start date/time might change, I'm not sure if that appended portion of the ID will change since google controls that.

**Comment by NovaFox161** [comment]
This should now no longer be an issue since all existing code relating to this has been removed/rewritten in order to convert to using slash commands
